package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class adminteacherController {
	@FXML
	private Button but_1;
	@FXML
	private Button but_3;
	@FXML
	private Button but_2;

	// Event Listener on Button[#but_1].onAction
	@FXML
	public void fresh(ActionEvent event) {
		// TODO Autogenerated
		Stage primaryStage1=new Stage();
		try {
			Parent root = FXMLLoader.load(getClass().getResource("fresht.fxml"));
			Scene scene = new Scene(root,400,130);
			 primaryStage1.setResizable(false);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage1.setScene(scene);
			primaryStage1.setTitle("重置教师密码");
			primaryStage1.show();
			aboutclass.setclass();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#but_2].onAction
	@FXML
	public void add(ActionEvent event) {
		// TODO Autogenerated
		Stage primaryStage1=new Stage();
		try {
			Parent root = FXMLLoader.load(getClass().getResource("addt.fxml"));
			Scene scene = new Scene(root,407,188);
			 primaryStage1.setResizable(false);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage1.setScene(scene);
			primaryStage1.setTitle("添加教师");
			primaryStage1.show();
			aboutclass.setclass();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#but_3].onAction
	@FXML
	public void del(ActionEvent event) {
		// TODO Autogenerated
		Stage primaryStage1=new Stage();
		try {
			Parent root = FXMLLoader.load(getClass().getResource("delt.fxml"));
			Scene scene = new Scene(root,423,121);
			 primaryStage1.setResizable(false);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage1.setScene(scene);
			primaryStage1.setTitle("删除教师");
			primaryStage1.show();
			aboutclass.setclass();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
}
