package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.xml.stream.events.StartDocument;

import javafx.event.ActionEvent;

public class adminstudentController {
	@FXML
	private Button but_1;
	@FXML
	private Button but_2;
	@FXML
	private Button but_3;
	
	// Event Listener on Button[#but_1].onAction
	@FXML
	public void fresh(ActionEvent event) {
		// TODO Autogenerated
		Stage primaryStage1=new Stage();
		try {
			Parent root = FXMLLoader.load(getClass().getResource("freshs.fxml"));
			Scene scene = new Scene(root,395,124);
			 primaryStage1.setResizable(false);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage1.setScene(scene);
			primaryStage1.setTitle("更改学生密码");
			primaryStage1.show();
			aboutclass.setclass();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#but_2].onAction
	@FXML
	public void add(ActionEvent event) {
		// TODO Autogenerated
		Stage primaryStage1=new Stage();
		try {
			Parent root = FXMLLoader.load(getClass().getResource("adds.fxml"));
			Scene scene = new Scene(root,407,193);
			 primaryStage1.setResizable(false);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage1.setScene(scene);
			primaryStage1.setTitle("添加学生");
			primaryStage1.show();
			aboutclass.setclass();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#but_3].onAction
	@FXML
	public void del(ActionEvent event) {
		// TODO Autogenerated
		Stage primaryStage1=new Stage();
		try {
			Parent root = FXMLLoader.load(getClass().getResource("dels.fxml"));
			Scene scene = new Scene(root,421,149);
			 primaryStage1.setResizable(false);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage1.setScene(scene);
			primaryStage1.setTitle("删除学生");
			primaryStage1.show();
			aboutclass.setclass();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
}
