package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class adminController {
	@FXML
	private Button but_1;
	@FXML
	private Button but_2;

	// Event Listener on Button[#but_1].onAction
	@FXML
	public void admint(ActionEvent event) {
		// TODO Autogenerated
//		Stage stage = (Stage)but_1.getScene().getWindow();
//	    stage.close();
		Stage primaryStage1=new Stage();
		try {
			Parent root = FXMLLoader.load(getClass().getResource("adminteacher.fxml"));
			Scene scene = new Scene(root,392,118);
			 primaryStage1.setResizable(false);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage1.setScene(scene);
			primaryStage1.setTitle("管理教师");
			primaryStage1.show();
			aboutclass.setclass();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#but_2].onAction
	@FXML
	public void admins(ActionEvent event) {
		// TODO Autogenerated
//		Stage stage = (Stage)but_2.getScene().getWindow();
//	    stage.close();
		Stage primaryStage1=new Stage();
		try {
			Parent root = FXMLLoader.load(getClass().getResource("adminstudent.fxml"));
			Scene scene = new Scene(root,371,128);
			 primaryStage1.setResizable(false);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage1.setScene(scene);
			primaryStage1.setTitle("管理学生");
			primaryStage1.show();
			aboutclass.setclass();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
}
