package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class tipsController {
	@FXML
	private Button but;

	// Event Listener on Button[#but].onAction
	@FXML
	public void but1(ActionEvent event) {
		// TODO Autogenerated
		Stage stage = (Stage)but.getScene().getWindow();
	    stage.close();
	}
}
