package application;
import java.util.Date;

import javafx.event.ActionEvent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.io.*;
public class writefile {
//将数据库的情况以.txt形式导出
	public static String getDateTimeAsString(LocalDateTime localDateTime,String format) {
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern(format);
		return localDateTime.format(formatter);
		}
	public static LocalDateTime parseStringToDateTime(String time,String format) {
		DateTimeFormatter df = DateTimeFormatter.ofPattern(format);
		return LocalDateTime.parse(time,df);
		}
	public static void write() throws IOException {
		// TODO Autogenerated
		//area.setText("");
			String driver = "com.mysql.jdbc.Driver";
			String url = "jdbc:mysql://localhost:3306/test";
			String uid = "root";
			String pwd = "root";
			Connection conn = null;
			Statement stmt = null;
			PreparedStatement pstmt = null;
			ResultSet rs = null;
			LocalDateTime times=LocalDateTime.now();
			String createdate = getDateTimeAsString(times, "yyyy-MM-dd HH:mm:ss");
			FileWriter fileWriter=new FileWriter("签到情况.txt");
			fileWriter.write("导出时间  "+createdate+"\r\n");

			try {
				Class.forName(driver);
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			try {
				conn = DriverManager.getConnection(url, uid, pwd);
				String sql = "select *from student";
				pstmt = conn.prepareStatement(sql);
				rs = pstmt.executeQuery();
				
				while (rs.next()) {
					int num = rs.getInt("number");
					String name0= rs.getString("name");
					String log = rs.getString("login");
					String tim = rs.getString("time");//写出读取数据
					fileWriter.write("学号 "+num+" ");
					fileWriter.write("姓名 "+name0+" ");
					fileWriter.write("签到情况  "+log+" ");
					fileWriter.write("操作时间  "+tim+" \n");
				}

			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} finally {
				try {
					rs.close();
					pstmt.close();
					conn.close();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}
			fileWriter.close();
			
	}
	
}
